### ISSUE TITLE
[[ -n: not found

### ISSUE THREAD

**Issue by roachsinai** [ppwwyyxx/dotfiles#2]
https://github.com/ppwwyyxx/dotfiles/blob/06c31ae166ae768baf0d8b5e20d5fe6e94665ae9/scripts/yank#L51

get error on Ubuntu 20.04, change shebang `sh -> bash` works.

**Comment by roachsinai** [comment]
Thanks for the yank script.

**Comment by ppwwyyxx** [comment]
Thanks!
